# Generated by Django 5.0.1 on 2024-01-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_name',
        ),
    ]
