# Generated by Django 5.0.1 on 2024-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_author_book_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
