# Generated by Django 5.0.1 on 2024-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
