# Generated by Django 5.0.1 on 2024-01-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_book_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_name',
            new_name='author',
        ),
    ]
